#!/usr/bin/env bash

SMF_ROOT=/var/svc/manifest/site
SVC_ROOT=/opt/podest/fanboy

copy() {
  if [ -n $( svcs fanboy | grep -sq online ) ]; then
    echo "fanboy appears to be online"
    exit 1
  fi
  mkdir -p $SVC_ROOT
  cp "${DIR}/../conf.js" $SVC_ROOT
  cp "${DIR}/../index.js" $SVC_ROOT
  cp "${DIR}/../package.json" $SVC_ROOT
  cp "${DIR}/../start.js" $SVC_ROOT
  cp -rf "${DIR}/../node_modules" $SVC_ROOT
}

import_manifest() {
  local manifest="${DIR}/../smf/manifests/fanboy.xml"
  cp "$manifest" "$SMF_ROOT"
  svcadm restart manifest-import
  svcadm enable fanboy
}

smartos() {
  copy
  import_manifest
}
