#!/usr/bin/env bash

SMF_ROOT=/var/svc/manifest/site
SVC_ROOT=/opt/podest/fanboy

check() {
  return $( svcs fanboy | grep -ic "online" )
}

copy() {
  mkdir -p $SVC_ROOT
  cp "${DIR}/../conf.js" $SVC_ROOT
  cp "${DIR}/../index.js" $SVC_ROOT
  cp "${DIR}/../package.json" $SVC_ROOT
  cp "${DIR}/../start.js" $SVC_ROOT
  cp -rf "${DIR}/../lib" $SVC_ROOT
  cp -rf "${DIR}/../node_modules" $SVC_ROOT
}

populate() {
  local in="${DIR}/fanboy.xml.in"
  local out="${DIR}/../smf/manifests/fanboy.xml"
  sed \
    -e "s;@@PORT@@;$PORT;g" \
    $in > $out
}

import_manifest() {
  local manifest="${DIR}/../smf/manifests/fanboy.xml"
  cp "$manifest" "$SMF_ROOT"
  svcadm restart manifest-import
  svcadm enable fanboy
}

smartos() {
  check || exit 1
  copy
  populate
  import_manifest
}
