#!/usr/bin/env bash

SMF_ROOT=/var/svc/manifest/site
SVC_ROOT=/opt/podest/fanboy

check() {
  local isOnline=$( svcs fanboy | grep -ic "online" )
  if [ $isOnline -eq 1 ]
  then
    echo "aborting: fanboy seems to be online"
    echo 1
  fi
  echo 0
}

copy() {
  mkdir -p $SVC_ROOT
  cp "${DIR}/../conf.js" $SVC_ROOT
  cp "${DIR}/../index.js" $SVC_ROOT
  cp "${DIR}/../package.json" $SVC_ROOT
  cp "${DIR}/../start.js" $SVC_ROOT
  cp -rf "${DIR}/../lib" $SVC_ROOT
  cp -rf "${DIR}/../node_modules" $SVC_ROOT
}

import_manifest() {
  local manifest="${DIR}/../smf/manifests/fanboy.xml"
  cp "$manifest" "$SMF_ROOT"
  svcadm restart manifest-import
  svcadm enable fanboy
}

smartos() {
  check
  copy
  import_manifest
}
